!TCL=3468, Auto-generated by Rajat's TextPad Syntax Generator Script
!TITLE=AutoHotkey
!SORT=Y
!TEXT=#AllowSameLineComments
#AllowSameLineComments
!
!TEXT=#ClipboardTimeout
#ClipboardTimeout milliseconds
!
!TEXT=#CommentFlag
#CommentFlag NewString
!
!TEXT=#ErrorStdOut
#ErrorStdOut
!
!TEXT=#EscapeChar
#EscapeChar NewChar
!
!TEXT=#HotkeyInterval
#HotkeyInterval Value
!
!TEXT=#HotkeyModifierTimeout
#HotkeyModifierTimeout milliseconds
!
!TEXT=#Hotstring
#Hotstring NewOptions
!
!TEXT=#IfWinActive
#IfWinActive [, WinTitle, WinText]
!
!TEXT=#IfWinExist
#IfWinExist [, WinTitle, WinText]
!
!TEXT=#IfWinNotActive
#IfWinNotActive [, WinTitle, WinText]
!
!TEXT=#IfWinNotExist
#IfWinNotExist [, WinTitle, WinText]
!
!TEXT=#Include
#Include FileName
!
!TEXT=#IncludeAgain
#IncludeAgain FileName
!
!TEXT=#InstallKeybdHook
#InstallKeybdHook
!
!TEXT=#InstallMouseHook
#InstallMouseHook
!
!TEXT=#KeyHistory
#KeyHistory MaxEvents
!
!TEXT=#LTrim
#LTrim On|Off
!
!TEXT=#MaxHotkeysPerInterval
#MaxHotkeysPerInterval Value
!
!TEXT=#MaxMem
#MaxMem ValueInMegabytes
!
!TEXT=#MaxThreads
#MaxThreads Value
!
!TEXT=#MaxThreadsBuffer
#MaxThreadsBuffer On|Off
!
!TEXT=#MaxThreadsPerHotkey
#MaxThreadsPerHotkey Value
!
!TEXT=#NoEnv
#NoEnv
!
!TEXT=#NoTrayIcon
#NoTrayIcon
!
!TEXT=#Persistent
#Persistent
!
!TEXT=#SingleInstance
#SingleInstance [force|ignore|off]
!
!TEXT=#UseHook
#UseHook [On|Off]
!
!TEXT=#WinActivateForce
#WinActivateForce
!
!TEXT=AutoTrim
AutoTrim, On|Off
!
!TEXT=BlockInput
BlockInput, On|Off|Send|Mouse|SendAndMouse|Default|MouseMove|MouseMoveOff
!
!TEXT=Break
Break
!
!TEXT=Click
Click
!
!TEXT=ClipWait
ClipWait [, SecondsToWait, 1]
!
!TEXT=Continue
Continue
!
!TEXT=Control
Control, Cmd [, Value, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=ControlClick
ControlClick [, Control-or-Pos, WinTitle, WinText, WhichButton, ClickCount, Options, ExcludeTitle, ExcludeText]
!
!TEXT=ControlFocus
ControlFocus [, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=ControlGet
ControlGet, OutputVar, Cmd [, Value, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=ControlGetFocus
ControlGetFocus, OutputVar [WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=ControlGetPos
ControlGetPos [, X, Y, Width, Height, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=ControlGetText
ControlGetText, OutputVar [, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=ControlMove
ControlMove, Control, X, Y, Width, Height [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=ControlSend
ControlSend [, Control, Keys, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=ControlSendRaw
ControlSendRaw [, Control, Keys, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=ControlSetText
ControlSetText, Control, NewText [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=CoordMode
CoordMode, ToolTip|Pixel|Mouse [, Screen|Relative]
!
!TEXT=Critical
Critical [, Off]
!
!TEXT=DetectHiddenText
DetectHiddenText, On|Off
!
!TEXT=DetectHiddenWindows
DetectHiddenWindows, On|Off
!
!TEXT=Drive
Drive, Sub-command [, Drive , Value]
!
!TEXT=DriveGet
DriveGet, OutputVar, Cmd [, Value]
!
!TEXT=DriveSpaceFree
DriveSpaceFree, OutputVar, C:\
!
!TEXT=Edit
Edit
!
!TEXT=Else
Else
!
!TEXT=EnvAdd
EnvAdd, Var, Value [, TimeUnits]
!
!TEXT=EnvDiv
EnvDiv, Var, Value
!
!TEXT=EnvGet
EnvGet, OutputVar, EnvVarName
!
!TEXT=EnvMult
EnvMult, Var, Value
!
!TEXT=EnvSet
EnvSet, EnvVar, Value
!
!TEXT=EnvSub
EnvSub, Var, Value [, TimeUnits]
!
!TEXT=EnvUpdate
EnvUpdate
!
!TEXT=Exit
Exit [, ExitCode]
!
!TEXT=ExitApp
ExitApp [, ExitCode]
!
!TEXT=FileAppend
FileAppend [, Text, Filename]
!
!TEXT=FileCopy
FileCopy, Source, Dest [, Flag (1 = overwrite)]
!
!TEXT=FileCopyDir
FileCopyDir, Source, Dest [, Flag]
!
!TEXT=FileCreateDir
FileCreateDir, Path
!
!TEXT=FileCreateShortcut
FileCreateShortcut, Target, C:\My Shortcut.lnk [, WorkingDir, Args, Description, IconFile, ShortcutKey, IconNumber, RunState]
!
!TEXT=FileDelete
FileDelete, FilePattern
!
!TEXT=FileGetAttrib
FileGetAttrib, OutputVar(RASHNDOCT) [, Filename]
!
!TEXT=FileGetShortcut
FileGetShortcut, LinkFile [, OutTarget, OutDir, OutArgs, OutDescription, OutIcon, OutIconNum, OutRunState]
!
!TEXT=FileGetSize
FileGetSize, OutputVar [, Filename, Units]
!
!TEXT=FileGetTime
FileGetTime, OutputVar [, Filename, WhichTime (M, C, or A -- default is M)]
!
!TEXT=FileGetVersion
FileGetVersion, OutputVar [, Filename]
!
!TEXT=FileInstall
FileInstall, Source, Dest [, Flag (1 = overwrite)]
!
!TEXT=FileMove
FileMove, Source, Dest [, Flag (1 = overwrite)]
!
!TEXT=FileMoveDir
FileMoveDir, Source, Dest [, Flag (2 = overwrite)]
!
!TEXT=FileRead
FileRead, OutputVar, Filename
!
!TEXT=FileReadLine
FileReadLine, OutputVar, Filename, LineNum
!
!TEXT=FileRecycle
FileRecycle, FilePattern
!
!TEXT=FileRecycleEmpty
FileRecycleEmpty [, C:\]
!
!TEXT=FileRemoveDir
FileRemoveDir, Path [, Recurse? (1 = yes)]
!
!TEXT=FileSelectFile
FileSelectFile, OutputVar [, Options, RootDir[\DefaultFilename], Prompt, Filter]
!
!TEXT=FileSelectFolder
FileSelectFolder, OutputVar [, *StartingFolder, Options, Prompt]
!
!TEXT=FileSetAttrib
FileSetAttrib, Attributes(+-^RASHNOT) [, FilePattern, OperateOnFolders?, Recurse?]
!
!TEXT=FileSetTime
FileSetTime [, YYYYMMDDHH24MISS, FilePattern, WhichTime (M|C|A), OperateOnFolders?, Recurse?]
!
!TEXT=FormatTime
FormatTime, OutputVar [, YYYYMMDDHH24MISS, Format]
!
!TEXT=GetKeyState
GetKeyState, OutputVar, WhichKey [, Mode (P|T)]
!
!TEXT=Gosub
Gosub, Label
!
!TEXT=Goto
Goto, Label
!
!TEXT=GroupActivate
GroupActivate, GroupName [, R]
!
!TEXT=GroupAdd
GroupAdd, GroupName, WinTitle [, WinText, Label, ExcludeTitle, ExcludeText]
!
!TEXT=GroupClose
GroupClose, GroupName [, A|R]
!
!TEXT=GroupDeactivate
GroupDeactivate, GroupName [, R]
!
!TEXT=Gui
Gui, sub-command [, Param2, Param3, Param4]
!
!TEXT=GuiControl
GuiControl, Sub-command, ControlID [, Param3]
!
!TEXT=GuiControlGet
GuiControlGet, OutputVar [, Sub-command, ControlID, Param4]
!
!TEXT=Hotkey
Hotkey, KeyName [, Label, Options]
!
!TEXT=If Else
If (var = "Value") | IfWinExist, WinTitle | etc.
{
	command1
	command2
}
Else
{
	command1
	command2
}
!
!TEXT=If Var [not] between Low and High
If Var [not] between Low and High
!
!TEXT=If Var [not] contains value1,value2,...
If Var [not] contains value1,value2,...
!
!TEXT=If Var [not] in value1,value2,...
If Var [not] in value1,value2,...
!
!TEXT=If Var is [not] integer|float|number|digit|xdigit|alpha|upper|lower|alnum|space|time
If Var is [not] integer|float|number|digit|xdigit|alpha|upper|lower|alnum|space|time
!
!TEXT=IfEqual
IfEqual, var, value
!
!TEXT=IfExist
IfExist, File|Dir|Pattern
!
!TEXT=IfGreater
IfGreater, var, value
!
!TEXT=IfGreaterOrEqual
IfGreaterOrEqual, var, value
!
!TEXT=IfInString
IfInString, Var, SearchString
!
!TEXT=IfLess
IfLess, var, value
!
!TEXT=IfLessOrEqual
IfLessOrEqual, var, value
!
!TEXT=IfMsgBox
IfMsgBox, Yes|No|OK|Cancel|Abort|Ignore|Retry|Timeout
!
!TEXT=IfNotEqual
IfNotEqual, var, value
!
!TEXT=IfNotExist
IfNotExist, File|Dir|Pattern
!
!TEXT=IfNotInString
IfNotInString, Var, SearchString
!
!TEXT=IfWinActive
IfWinActive [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=IfWinExist
IfWinExist [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=IfWinNotActive
IfWinNotActive [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=IfWinNotExist
IfWinNotExist [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=ImageSearch
ImageSearch, OutputVarX, OutputVarY, X1, Y1, X2, Y2, ImageFile
!
!TEXT=IniDelete
IniDelete, Filename, Section [, Key]
!
!TEXT=IniRead
IniRead, OutputVar, Filename, Section, Key [, Default]
!
!TEXT=IniWrite
IniWrite, Value, Filename, Section, Key
!
!TEXT=Input
Input [, OutputVar, Options, EndKeys, MatchList]
!
!TEXT=InputBox
InputBox, OutputVar [, Title, Prompt, HIDE, Width, Height, X, Y, Font, Timeout, Default]
!
!TEXT=KeyHistory
KeyHistory
!
!TEXT=KeyWait
KeyWait, KeyName [, Options]
!
!TEXT=ListHotkeys
ListHotkeys
!
!TEXT=ListLines
ListLines
!
!TEXT=ListVars
ListVars
!
!TEXT=Loop
Loop [, Count]
{
	ID := A_Index
	If var%A_Index% =
	break
}
!
!TEXT=Loop, FilePattern
Loop, FilePattern [, IncludeFolders?, Recurse?]
{
	FileName := A_LoopFileName
	FileFullPath := A_LoopFileLongPath
	FileRelativeDir := A_LoopFileDir
	command2
}
!
!TEXT=Loop, Parse
Loop, Parse, InputVar [, Delimiters|CSV, OmitChars]
{
	Line := A_LoopField
	command2
}
!
!TEXT=Loop, Read
Loop, Read, InputFile [, OutputFile]
{
	Line := A_LoopReadLine
	command2
}
!
!TEXT=Loop, Reg
Loop, HKLM|HKU|HKCU|HKCR|HKCC [, Key, IncludeSubkeys?, Recurse?]
{
	RegName := A_LoopRegName
	RegType := A_LoopRegType
	command2
}
!
!TEXT=Menu
Menu, MenuName, Cmd [, P3, P4, P5]
!
!TEXT=MouseClick
MouseClick, WhichButton [, X, Y, ClickCount, Speed, D|U, R]
!
!TEXT=MouseClickDrag
MouseClickDrag, WhichButton, X1, Y1, X2, Y2 [, Speed, R]
!
!TEXT=MouseGetPos
MouseGetPos [, OutputVarX, OutputVarY, OutputVarWin, OutputVarControl, 1|2|3]
!
!TEXT=MouseMove
MouseMove, X, Y [, Speed, R]
!
!TEXT=MsgBox
MsgBox [, Options, Title, Text, Timeout]
!
!TEXT=OnExit
OnExit [, Label]
!
!TEXT=OutputDebug
OutputDebug, Text
!
!TEXT=Pause
Pause [, On|Off|Toggle, OperateOnUnderlyingThread?]
!
!TEXT=PixelGetColor
PixelGetColor, OutputVar, X, Y [, Alt|Slow|RGB]
!
!TEXT=PixelSearch
PixelSearch, OutputVarX, OutputVarY, X1, Y1, X2, Y2, ColorID [, Variation, Fast|RGB]
!
!TEXT=PostMessage
PostMessage, Msg [, wParam, lParam, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=Process
Process, Cmd, PID-or-Name [, Param3]
!
!TEXT=Progress
Progress, Param1 [, SubText, MainText, WinTitle, FontName]
!
!TEXT=Random
Random, OutputVar [, Min, Max]
!
!TEXT=RegDelete
RegDelete, HKLM|HKU|HKCU|HKCR|HKCC, SubKey [, ValueName]
!
!TEXT=RegRead
RegRead, OutputVar, HKLM|HKU|HKCU|HKCR|HKCC, SubKey [, ValueName]
!
!TEXT=RegWrite
RegWrite, REG_SZ|REG_EXPAND_SZ|REG_MULTI_SZ|REG_DWORD|REG_BINARY, HKLM|HKU|HKCU|HKCR|HKCC, SubKey [, ValueName, Value]
!
!TEXT=Reload
Reload
!
!TEXT=Repeat
Repeat
!
!TEXT=Return
Return [, Expression]
!
!TEXT=Run
Run, Target [, WorkingDir, Max|Min|Hide|UseErrorLevel, OutputVarPID]
!
!TEXT=RunAs
RunAs [, User, Password, Domain] 
!
!TEXT=RunWait
RunWait, Target [, WorkingDir, Max|Min|Hide|UseErrorLevel, OutputVarPID]
!
!TEXT=Send
Send, Keys
!
!TEXT=SendEvent
SendEvent, Keys
!
!TEXT=SendInput
SendInput, Keys
!
!TEXT=SendMessage
SendMessage, Msg [, wParam, lParam, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=SendMode
SendMode, Event|Play|Input|InputThenPlay
!
!TEXT=SendPlay
SendPlay, Keys
!
!TEXT=SendRaw
SendRaw, Keys
!
!TEXT=SetBatchLines
SetBatchLines, -1 | 20ms | LineCount
!
!TEXT=SetCapslockState
SetCapsLockState, On|Off|AlwaysOn|AlwaysOff
!
!TEXT=SetControlDelay
SetControlDelay, Delay
!
!TEXT=SetDefaultMouseSpeed
SetDefaultMouseSpeed, Speed
!
!TEXT=SetEnv
SetEnv, Var, Value
!
!TEXT=SetFormat
SetFormat, float|integer, TotalWidth.DecimalPlaces|hex|d
!
!TEXT=SetKeyDelay
SetKeyDelay [, Delay, PressDuration]
!
!TEXT=SetMouseDelay
SetMouseDelay, Delay
!
!TEXT=SetNumlockState
SetNumLockState, On|Off|AlwaysOn|AlwaysOff
!
!TEXT=SetScrollLockState
SetScrollLockState, On|Off|AlwaysOn|AlwaysOff
!
!TEXT=SetStoreCapslockMode
SetStoreCapslockMode, On|Off
!
!TEXT=SetTimer
SetTimer, Label [, Period|On|Off]
!
!TEXT=SetTitleMatchMode
SetTitleMatchMode, Fast|Slow|RegEx|1|2|3
!
!TEXT=SetWinDelay
SetWinDelay, Delay
!
!TEXT=SetWorkingDir
SetWorkingDir, DirName
!
!TEXT=Shutdown
Shutdown, Code
!
!TEXT=Sleep
Sleep, Delay
!
!TEXT=Sort
Sort, VarName [, Options]
!
!TEXT=SoundBeep
SoundBeep [, Frequency, Duration]
!
!TEXT=SoundGet
SoundGet, OutputVar [, ComponentType, ControlType, DeviceNumber]
!
!TEXT=SoundGetWaveVolume
SoundGetWaveVolume, OutputVar [, DeviceNumber]
!
!TEXT=SoundPlay
SoundPlay, Filename [, wait]
!
!TEXT=SoundSet
SoundSet, NewSetting [, ComponentType, ControlType, DeviceNumber]
!
!TEXT=SoundSetWaveVolume
SoundSetWaveVolume, Percent [, DeviceNumber]
!
!TEXT=SplashImage
SplashImage [, ImageFile, Options, SubText, MainText, WinTitle, FontName]
!
!TEXT=SplashTextOff
SplashTextOff
!
!TEXT=SplashTextOn
SplashTextOn [, Width, Height, Title, Text]
!
!TEXT=SplitPath
SplitPath, InputVar [, OutFileName, OutDir, OutExtension, OutNameNoExt, OutDrive]
!
!TEXT=StatusBarGetText
StatusBarGetText, OutputVar [, Part#, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=StatusBarWait
StatusBarWait [, BarText, Seconds, Part#, WinTitle, WinText, Interval, ExcludeTitle, ExcludeText]
!
!TEXT=StringCaseSense
StringCaseSense, On|Off|Locale
!
!TEXT=StringGetPos
StringGetPos, OutputVar, InputVar, SearchText [, L#|R#, Offset]
!
!TEXT=StringLeft
StringLeft, OutputVar, InputVar, Count
!
!TEXT=StringLen
StringLen, OutputVar, InputVar
!
!TEXT=StringLower
StringLower, OutputVar, InputVar [, T]
!
!TEXT=StringMid
StringMid, OutputVar, InputVar, StartChar [, Count, L]
!
!TEXT=StringReplace
StringReplace, OutputVar, InputVar, SearchText [, ReplaceText, All]
!
!TEXT=StringRight
StringRight, OutputVar, InputVar, Count
!
!TEXT=StringSplit
StringSplit, OutputArray, InputVar [, Delimiters, OmitChars]
!
!TEXT=StringTrimLeft
StringTrimLeft, OutputVar, InputVar, Count
!
!TEXT=StringTrimRight
StringTrimRight, OutputVar, InputVar, Count
!
!TEXT=StringUpper
StringUpper, OutputVar, InputVar [, T]
!
!TEXT=Suspend
Suspend [, On|Off|Toggle|Permit]
!
!TEXT=SysGet
SysGet, OutputVar, Sub-command [, Param3]
!
!TEXT=Thread
Thread, Setting, P2 [, P3]
!
!TEXT=ToolTip
ToolTip [, Text, X, Y, WhichToolTip]
!
!TEXT=Transform
Transform, OutputVar, Cmd, Value1 [, Value2]
!
!TEXT=TrayTip
TrayTip [, Title, Text, Seconds, Options]
!
!TEXT=URLDownloadToFile
URLDownloadToFile, URL, Filename
!
!TEXT=While
While, Expression
!
!TEXT=WinActivate
WinActivate [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinActivateBottom
WinActivateBottom [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinClose
WinClose [, WinTitle, WinText, SecondsToWait, ExcludeTitle, ExcludeText]
!
!TEXT=WinGet
WinGet, OutputVar [, Cmd, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinGetActiveStats
WinGetActiveStats, Title, Width, Height, X, Y
!
!TEXT=WinGetActiveTitle
WinGetActiveTitle, OutputVar
!
!TEXT=WinGetClass
WinGetClass, OutputVar [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinGetPos
WinGetPos [, X, Y, Width, Height, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinGetText
WinGetText, OutputVar [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinGetTitle
WinGetTitle, OutputVar [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinHide
WinHide [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinKill
WinKill [, WinTitle, WinText, SecondsToWait, ExcludeTitle, ExcludeText]
!
!TEXT=WinMaximize
WinMaximize [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinMenuSelectItem
WinMenuSelectItem, WinTitle, WinText, Menu [, SubMenu1, SubMenu2, SubMenu3, SubMenu4, SubMenu5, SubMenu6, ExcludeTitle, ExcludeText]
!
!TEXT=WinMinimize
WinMinimize [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinMinimizeAll
WinMinimizeAll
!
!TEXT=WinMinimizeAllUndo
WinMinimizeAllUndo
!
!TEXT=WinMove
WinMove, WinTitle, WinText, X, Y [, Width, Height, ExcludeTitle, ExcludeText]
!
!TEXT=WinRestore
WinRestore [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinSet
WinSet, AlwaysOnTop|Trans, On|Off|Toggle|Value(0-255) [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinSetTitle
WinSetTitle, WinTitle, WinText, NewTitle [, ExcludeTitle, ExcludeText]
!
!TEXT=WinShow
WinShow [, WinTitle, WinText, ExcludeTitle, ExcludeText]
!
!TEXT=WinWait
WinWait, WinTitle, WinText, Seconds [, ExcludeTitle, ExcludeText]
!
!TEXT=WinWaitActive
WinWaitActive [, WinTitle, WinText, Seconds, ExcludeTitle, ExcludeText]
!
!TEXT=WinWaitClose
WinWaitClose, WinTitle, WinText, Seconds [, ExcludeTitle, ExcludeText]
!
!TEXT=WinWaitNotActive
WinWaitNotActive [, WinTitle, WinText, Seconds, ExcludeTitle, ExcludeText]
!
!TEXT=A_AhkPath
A_AhkPath
!
!TEXT=A_AhkVersion
A_AhkVersion
!
!TEXT=A_AppData
A_AppData
!
!TEXT=A_AppDataCommon
A_AppDataCommon
!
!TEXT=A_AutoTrim
A_AutoTrim
!
!TEXT=A_BatchLines
A_BatchLines
!
!TEXT=A_CaretX
A_CaretX
!
!TEXT=A_CaretY
A_CaretY
!
!TEXT=A_ComputerName
A_ComputerName
!
!TEXT=A_ControlDelay
A_ControlDelay
!
!TEXT=A_Cursor
A_Cursor
!
!TEXT=A_DD
A_DD
!
!TEXT=A_DDD
A_DDD
!
!TEXT=A_DDDD
A_DDDD
!
!TEXT=A_DefaultMouseSpeed
A_DefaultMouseSpeed
!
!TEXT=A_Desktop
A_Desktop
!
!TEXT=A_DesktopCommon
A_DesktopCommon
!
!TEXT=A_DetectHiddenText
A_DetectHiddenText
!
!TEXT=A_DetectHiddenWindows
A_DetectHiddenWindows
!
!TEXT=A_EndChar
A_EndChar
!
!TEXT=A_EventInfo
A_EventInfo
!
!TEXT=A_ExitReason
A_ExitReason
!
!TEXT=A_FormatFloat
A_FormatFloat
!
!TEXT=A_FormatInteger
A_FormatInteger
!
!TEXT=A_Gui
A_Gui
!
!TEXT=A_GuiEvent
A_GuiEvent
!
!TEXT=A_GuiControl
A_GuiControl
!
!TEXT=A_GuiControlEvent
A_GuiControlEvent
!
!TEXT=A_GuiHeight
A_GuiHeight
!
!TEXT=A_GuiWidth
A_GuiWidth
!
!TEXT=A_GuiX
A_GuiX
!
!TEXT=A_GuiY
A_GuiY
!
!TEXT=A_Hour
A_Hour
!
!TEXT=A_IconFile
A_IconFile
!
!TEXT=A_IconHidden
A_IconHidden
!
!TEXT=A_IconNumber
A_IconNumber
!
!TEXT=A_IconTip
A_IconTip
!
!TEXT=A_Index
A_Index
!
!TEXT=A_IPAddress1
A_IPAddress1
!
!TEXT=A_IPAddress2
A_IPAddress2
!
!TEXT=A_IPAddress3
A_IPAddress3
!
!TEXT=A_IPAddress4
A_IPAddress4
!
!TEXT=A_ISAdmin
A_ISAdmin
!
!TEXT=A_IsCompiled
A_IsCompiled
!
!TEXT=A_IsCritical
A_IsCritical
!
!TEXT=A_IsPaused
A_IsPaused
!
!TEXT=A_IsSuspended
A_IsSuspended
!
!TEXT=A_KeyDelay
A_KeyDelay
!
!TEXT=A_Language
A_Language
!
!TEXT=A_LastError
A_LastError
!
!TEXT=A_LineFile
A_LineFile
!
!TEXT=A_LineNumber
A_LineNumber
!
!TEXT=A_LoopField
A_LoopField
!
!TEXT=A_LoopFileAttrib
A_LoopFileAttrib
!
!TEXT=A_LoopFileDir
A_LoopFileDir
!
!TEXT=A_LoopFileExt
A_LoopFileExt
!
!TEXT=A_LoopFileFullPath
A_LoopFileFullPath
!
!TEXT=A_LoopFileLongPath
A_LoopFileLongPath
!
!TEXT=A_LoopFileName
A_LoopFileName
!
!TEXT=A_LoopFileShortName
A_LoopFileShortName
!
!TEXT=A_LoopFileShortPath
A_LoopFileShortPath
!
!TEXT=A_LoopFileSize
A_LoopFileSize
!
!TEXT=A_LoopFileSizeKB
A_LoopFileSizeKB
!
!TEXT=A_LoopFileSizeMB
A_LoopFileSizeMB
!
!TEXT=A_LoopFileTimeAccessed
A_LoopFileTimeAccessed
!
!TEXT=A_LoopFileTimeCreated
A_LoopFileTimeCreated
!
!TEXT=A_LoopFileTimeModified
A_LoopFileTimeModified
!
!TEXT=A_LoopReadLine
A_LoopReadLine
!
!TEXT=A_LoopRegKey
A_LoopRegKey
!
!TEXT=A_LoopRegName
A_LoopRegName
!
!TEXT=A_LoopRegSubkey
A_LoopRegSubkey
!
!TEXT=A_LoopRegTimeModified
A_LoopRegTimeModified
!
!TEXT=A_LoopRegType
A_LoopRegType
!
!TEXT=A_MDAY
A_MDAY
!
!TEXT=A_Min
A_Min
!
!TEXT=A_MM
A_MM
!
!TEXT=A_MMM
A_MMM
!
!TEXT=A_MMMM
A_MMMM
!
!TEXT=A_Mon
A_Mon
!
!TEXT=A_MouseDelay
A_MouseDelay
!
!TEXT=A_MSec
A_MSec
!
!TEXT=A_MyDocuments
A_MyDocuments
!
!TEXT=A_Now
A_Now
!
!TEXT=A_NowUTC
A_NowUTC
!
!TEXT=A_NumBatchLines
A_NumBatchLines
!
!TEXT=A_OSType
A_OSType
!
!TEXT=A_OSVersion
A_OSVersion
!
!TEXT=A_PriorHotkey
A_PriorHotkey
!
!TEXT=A_ProgramFiles
A_ProgramFiles
!
!TEXT=A_Programs
A_Programs
!
!TEXT=A_ProgramsCommon
A_ProgramsCommon
!
!TEXT=A_ScreenHeight
A_ScreenHeight
!
!TEXT=A_ScreenWidth
A_ScreenWidth
!
!TEXT=A_ScriptDir
A_ScriptDir
!
!TEXT=A_ScriptFullPath
A_ScriptFullPath
!
!TEXT=A_ScriptName
A_ScriptName
!
!TEXT=A_Sec
A_Sec
!
!TEXT=A_Space
A_Space
!
!TEXT=A_StartMenu
A_StartMenu
!
!TEXT=A_StartMenuCommon
A_StartMenuCommon
!
!TEXT=A_Startup
A_Startup
!
!TEXT=A_StartupCommon
A_StartupCommon
!
!TEXT=A_StringCaseSense
A_StringCaseSense
!
!TEXT=A_Tab
A_Tab
!
!TEXT=A_Temp
A_Temp
!
!TEXT=A_ThisFunc
A_ThisFunc
!
!TEXT=A_ThisHotkey
A_ThisHotkey
!
!TEXT=A_ThisLabel
A_ThisLabel
!
!TEXT=A_ThisMenu
A_ThisMenu
!
!TEXT=A_ThisMenuItem
A_ThisMenuItem
!
!TEXT=A_ThisMenuItemPos
A_ThisMenuItemPos
!
!TEXT=A_TickCount
A_TickCount
!
!TEXT=A_TimeIdle
A_TimeIdle
!
!TEXT=A_TimeIdlePhysical
A_TimeIdlePhysical
!
!TEXT=A_TimeSincePriorHotkey
A_TimeSincePriorHotkey
!
!TEXT=A_TimeSinceThisHotkey
A_TimeSinceThisHotkey
!
!TEXT=A_TitleMatchMode
A_TitleMatchMode
!
!TEXT=A_TitleMatchModeSpeed
A_TitleMatchModeSpeed
!
!TEXT=A_UserName
A_UserName
!
!TEXT=A_WDay
A_WDay
!
!TEXT=A_WinDelay
A_WinDelay
!
!TEXT=A_WinDir
A_WinDir
!
!TEXT=A_WorkingDir
A_WorkingDir
!
!TEXT=A_YDay
A_YDay
!
!TEXT=A_YEAR
A_YEAR
!
!TEXT=A_YWeek
A_YWeek
!
!TEXT=A_YYYY
A_YYYY
!
!TEXT=Clipboard
Clipboard
!
!TEXT=ClipboardAll
ClipboardAll
!
!TEXT=ComSpec
ComSpec
!
!TEXT=ErrorLevel
ErrorLevel
!
!TEXT=ProgramFiles
ProgramFiles
!
!TEXT=True
True
!
!TEXT=False
False
!
